//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHomework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupation
    {
        public Occupation()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int OccupationId { get; set; }
        public string OccupationName { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
